### ISSUE TITLE
Create pipeline to deploy testing-platform on the testserver

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/odh-testingplatform#2]
- [x] Write documentation about how to setup the testing platform (Davide Montesin) @davidebz
-  [x] create pipeline to deploy to test environment

**Comment by bertolla** [comment]
@sseppi Visit http://tomcat.testingmachine.eu/testingplatform/ to test it

**Comment by Piiit** [comment]
The problem is the Tomcat server itself, deployment does no longer work ... we will check this today. The link above should then work again... there is nothing on production right now

**Comment by Piiit** [comment]
@bertolla Fixes the test server (https://github.com/idm-suedtirol/server-deployment/issues/36)... Later, @alexlanz will create a deployment script for our production server, when @davidebz created a new script version bundled as .war file...
